(#281) Bump GH-Action images to latest
cake-contrib/Cake.Codecov pull request #282
Opened 2023-10-18 19:28 UTC by nils-a

and added the required dotnet versions.

fixes #281

2023-10-18 22:04 UTC, nils-a commented
@AdmiringWorm Everything is working again, apart from mergify which seems to be broken because of https://blog.mergify.com/strict-mode-deprecation/. However, I have no idea how to fix that in a meaningful way.

2024-05-02 10:29 UTC, AdmiringWorm requested changes
Thanks for putting this PR up, a few changes but I'll take care of them before merging it in.

2024-05-02 10:29 UTC, AdmiringWorm commented on .github/workflows/build.yml
> +          key: ${{ runner.os }}-tools-${{ hashFiles('setup.cake') }}-${{ hashFiles('.config/dotnet-tools.json') }}
The version of cake is the only dotnet-tool used, and it is explicitly set in this workflow, as such there is no need to change the cache key here.

2024-05-02 10:29 UTC, AdmiringWorm commented on .github/workflows/build.yml
> +        os: [windows-2022, ubuntu-22.04, macos-12]
```suggestion
        os: [windows-2022, ubuntu-22.04, macos-13]
```

2024-05-02 11:04 UTC, AdmiringWorm commented
This have been merged in commit https://github.com/cake-contrib/Cake.Codecov/commit/2796c0255f1e1ac788753bc5f587c55b28b67bb0

2024-05-02 11:04 UTC, closed without merging

2024-05-02 11:05 UTC, AdmiringWorm commented
@all-contributors please add @nils-a for code